### ISSUE TITLE
gosugamers-match@2

### ISSUE THREAD

**Issue by kenany** [kenany/gosugamers-matches#3]

**Comment by KenanY** [comment]
Found a bug https://github.com/KenanY/gosugamers-match/issues/7

**Comment by KenanY** [comment]
KenanY/gosugamers-match#7 has been fixed in [`gosugamers-match@2.0.1`](https://github.com/KenanY/gosugamers-match/releases/tag/2.0.1) so better make sure we depend on versions `>=` to that.
